//
// Actionはシステム全体で一意である必要がある。
//

export const PAGE_CONTROLLER_GENDER                 = "PAGE_CONTROLLER_GENDER";
export const PAGE_CONTROLLER_EVENT                  = "PAGE_CONTROLLER_EVENT";
export const PAGE_CONTROLLER_CLASSIFICATION         = "PAGE_CONTROLLER_CLASSIFICATION";
export const PAGE_CONTROLLER_SUBDIVISION            = "PAGE_CONTROLLER_SUBDIVISION";
export const PAGE_CONTROLLER_COMPETITION_GROUP      = "PAGE_CONTROLLER_COMPETITION_GROUP";
export const PAGE_CONTROLLER_BIBS                   = "PAGE_CONTROLLER_BIBS";

export const PAGE_INITIALIZE_COMPETITION            = "PAGE_INITIALIZE_COMPETITION";
export const PAGE_INITIALIZE_SUBDIVISION            = "PAGE_INITIALIZE_SUBDIVISION";
export const PAGE_INITIALIZE_COMPETITION_GROUP      = "PAGE_INITIALIZE_COMPETITION_GROUP";
export const PAGE_INITIALIZE_BIBS                   = "PAGE_INITIALIZE_BIBS";
export const PAGE_INITIALIZE_INPUT                  = "PAGE_INITIALIZE_INPUT";

export const DAY_REQUEST                            = 'DAY_REQUEST';
export const DAY_SUCCESS                            = 'DAY_SUCCESS';
export const DAY_FAILURE                            = 'DAY_FAILURE';

export const TOURNAMENT_REQUEST                     = 'TOURNAMENT_REQUEST';
export const TOURNAMENT_SUCCESS                     = 'TOURNAMENT_SUCCESS';
export const TOURNAMENT_FAILURE                     = 'TOURNAMENT_FAILURE';

export const TOURNAMENT_EVENT_REQUEST              = 'TOURNAMENT_EVENT_REQUEST';
export const TOURNAMENT_EVENT_SUCCESS              = 'TOURNAMENT_EVENT_SUCCESS';
export const TOURNAMENT_EVENT_FAILURE              = 'TOURNAMENT_EVENT_FAILURE';

export const SUBDIVISIONS_REQUEST                   = 'SUBDIVISIONS_REQUEST';
export const SUBDIVISIONS_SUCCESS                   = 'SUBDIVISIONS_SUCCESS';
export const SUBDIVISIONS_FAILURE                   = 'SUBDIVISIONS_FAILURE';
export const SUBDIVISIONS_PLAYER_SEQUENCE           = 'SUBDIVISIONS_PLAYER_SEQUENCE';
export const SUBDIVISIONS_PLAYER_SORT_SEQUENCE      = 'SUBDIVISIONS_PLAYER_SORT_SEQUENCE';
export const SUBDIVISIONS_PLAYER_SORT_BIBS          = 'SUBDIVISIONS_PLAYER_SORT_BIBS';

export const PARTICIPATING_PLAYERS_REQUEST          = "PARTICIPATING_PLAYERS_REQUEST";
export const PARTICIPATING_PLAYERS_SUCCESS          = "PARTICIPATING_PLAYERS_SUCCESS";
export const PARTICIPATING_PLAYERS_FAILURE          = "PARTICIPATING_PLAYERS_FAILURE";

export const EVENT_RESULT_REQUEST                   = "EVENT_RESULT_REQUEST";
export const EVENT_RESULT_SUCCESS                   = "EVENT_RESULT_SUCCESS";
export const EVENT_RESULT_FAILURE                   = "EVENT_RESULT_FAILURE";
