//
// Actionはシステム全体で一意である必要がある。
//

export const PAGE_CONTROLLER_GENDER                 = "PAGE_CONTROLLER_GENDER";
export const PAGE_CONTROLLER_EVENT                  = "PAGE_CONTROLLER_EVENT";
export const PAGE_CONTROLLER_CLASSIFICATION         = "PAGE_CONTROLLER_CLASSIFICATION";
export const PAGE_CONTROLLER_SUBDIVISION            = "PAGE_CONTROLLER_SUBDIVISION";
export const PAGE_CONTROLLER_COMPETITION_GROUP      = "PAGE_CONTROLLER_COMPETITION_GROUP";
export const PAGE_CONTROLLER_BIBS                   = "PAGE_CONTROLLER_BIBS";

export const PAGE_INITIALIZE_COMPETITION            = "PAGE_INITIALIZE_COMPETITION";
export const PAGE_INITIALIZE_SUBDIVISION            = "PAGE_INITIALIZE_SUBDIVISION";
export const PAGE_INITIALIZE_COMPETITION_GROUP      = "PAGE_INITIALIZE_COMPETITION_GROUP";
export const PAGE_INITIALIZE_BIBS                   = "PAGE_INITIALIZE_BIBS";
export const PAGE_INITIALIZE_INPUT                  = "PAGE_INITIALIZE_INPUT";

export const DAY_REQUEST                            = 'DAY_REQUEST';
export const DAY_SUCCESS                            = 'DAY_SUCCESS';
export const DAY_FAILURE                            = 'DAY_FAILURE';

export const TOURNAMENT_EVENTS_REQUEST              = 'TOURNAMENT_EVENTS_REQUEST';
export const TOURNAMENT_EVENTS_SUCCESS              = 'TOURNAMENT_EVENTS_SUCCESS';
export const TOURNAMENT_EVENTS_FAILURE              = 'TOURNAMENT_EVENTS_FAILURE';

export const SUBDIVISIONS_REQUEST                   = 'SUBDIVISIONS_REQUEST';
export const SUBDIVISIONS_SUCCESS                   = 'SUBDIVISIONS_SUCCESS';
export const SUBDIVISIONS_FAILURE                   = 'SUBDIVISIONS_FAILURE';

export const PARTICIPATING_PLAYERS_REQUEST          = "PARTICIPATING_PLAYERS_REQUEST";
export const PARTICIPATING_PLAYERS_SUCCESS          = "PARTICIPATING_PLAYERS_SUCCESS";
export const PARTICIPATING_PLAYERS_FAILURE          = "PARTICIPATING_PLAYERS_FAILURE";
